### ISSUE TITLE
교재 오타 찾기 제출물

### ISSUE THREAD

**Issue by moy8502** [kangwonlee/nmisp#174]
2015110016 기계공학과 문영우  eca21c반. 오타찾기 제출합니다.

1.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/00_introduction/00_introduction.ipynb?short_path=4498f12#L125

125행 [*딸린식구*] (members) 를 [*구성요소*] 로 바꾼다면 덜 어색할 것이라고 생각합니다.

2.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/00_introduction/30_python_review_2.ipynb?short_path=cab1500#L706

[반환한 후에도 수명을 유지한다] --> [반환한 후에도 변수값을 유지한다. or 변수값이 지속된다.] 로 바꾼다면 덜 어색할 것이라고 생각합니다.

3.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/00_introduction/40_how_to_draw_a_circle.ipynb?short_path=eb8bb21#L119

[위 두 닫힌 형태의 양함수를 그려보자] --> [(아래) 두개의 닫힌 형태 양함수(종속변수의 값이 독립변수의 값에서 직접 산출되는 함수)를 그려보자.] 로 바꾼다면 양함수의 개념을 더 매끄럽게 이해할 수 있을 것이라고 생각합니다.

4.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/00_introduction/50_pandas.ipynb?short_path=3ae9221#L255

[shift 메소드로] --> [shift의 방법으로 or shift를 사용하여]  로 바꾸는 것이 매끄러울 것으로 생각됩니다.

 
5.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/30_num_int/10_first_order.ipynb?short_path=10127a1#L215

[사다리꼴의 좌표를 나눔.]  --> [사다리꼴의 좌표들을 구함. or 사다리꼴의 좌표들을 설정.] 으로 바꾸는 것이 매끄러울 것으로 생각합니다.

6.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/30_num_int/20_second_order.ipynb?short_path=a390c86#L685

[1/4 원] --> [사분원(1/4 원) ] 으로 표기해 둔다면 가독성이 좋아질 것이라고 생각합니다. 

7.
https://github.com/kangwonlee/nmisp/blob/431a8d07c478097fb3b6fd7506ee5dcb49e40ae1/20_probability/10_probability.ipynb?short_path=31b368b#L7

[우직한 방식의 확률 계산] ----> [무차별 대입을 통한 확률 계산 혹은 우직한 방식( 무차별 대입 ) ] 으로의 추가설명은 직관적 이해해 효율적일 것이라고 생각합니다.

**Comment by kangwonlee** [comment]
@moy8502 수고 많습니다

제시한 의견 검토 중입니다. 대체로 내용을 더 매끄럽게 개선하려는 여러 시도로 이해되었습니다.

반영 여부를 아직 결정하지는 않았습니다. 몇 항목에 대한 현재의 의견을 아래에 적어 보았습니다.

4. 여기서 메소드 는 객체지향 프로그래밍 (OOP) 용어로 사용한 것입니다.

5. `pylab.linspace()` 함수가 `-r` 부터 `r` 사이의 구간을 `n+1`개로 *나누는* 것을 나타내려고 했던 것입니다.

참고 바랍니다.

**Comment by kangwonlee** [comment]
* [ ] 3. 양함수 b79d076
* [ ] 4. 메소드 ed2441f
